CREATE TABLE IF NOT EXISTS all_users(
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    email VARCHAR(20) DEFAULT NULL,
    login VARCHAR(20),
    birthDate TIMESTAMP DEFAULT NULL,
    friends INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(64),
    description VARCHAR(255),
    releaseDate TIMESTAMP DEFAULT NULL,
    duration INTEGER DEFAULT NULL,
    likes INTEGER DEFAULT NULL,
    filmGenre VARCHAR(10) DEFAULT NULL,
    filmMPArate VARCHAR(5) DEFAULT NULL,
    popleWhoLiked INTEGER DEFAULT NULL,
	FOREIGN KEY (popleWhoLiked) REFERENCES all_users(user_id)
);